//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u19074362_HW5_2._5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraydatabaseEntities : DbContext
    {
        public libraydatabaseEntities()
            : base("name=libraydatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<Category_table> Category_tables { get; set; }
        public virtual DbSet<publisher> publishers { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<issuebook> issuebooks { get; set; }
        public virtual DbSet<returnbook> returnbooks { get; set; }
    }
}
